spring:
  datasource:
    url: jdbc:postgresql://postgres:5432/deal_db
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: true

  liquibase:
    change-log: classpath:db/changelog/changelog-master.yaml
    enabled: true
    user: postgres
    password: postgres

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace