spring:
  datasource:
    driver-class-name: org.postgresql.Driver
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/master-test.yaml
    user: postgres
    password: postgres
    parameters:
      logLevel: DEBUG

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate.format_sql: true

logging:
  level:
    root: INFO
    ru.homework.contractor: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    liquibase: DEBUG
    org.springframework.jdbc: DEBUG